/** Admin 主库配置 */
export enum ConfigEnum {
	DB_TYPE = 'DB_TYPE',
	DB_HOST = 'DB_HOST',
	DB_PORT = 'DB_PORT',
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_DATABASE = 'DB_DATABASE',
	DB_SYNC = 'DB_SYNC',
	DB_POOL_SIZE = 'DB_POOL_SIZE',
	SECRET = 'SECRET',
}

/** AI 业务库（命名连接 `ai`） */
export enum AiDbEnum {
	AI_DB_ENABLED = 'AI_DB_ENABLED',
	AI_DB_HOST = 'AI_DB_HOST',
	AI_DB_PORT = 'AI_DB_PORT',
	AI_DB_USERNAME = 'AI_DB_USERNAME',
	AI_DB_PASSWORD = 'AI_DB_PASSWORD',
	AI_DB_DATABASE = 'AI_DB_DATABASE',
	AI_DB_POOL_SIZE = 'AI_DB_POOL_SIZE',
}

export enum LogEnum {
	LOG_LEVEL = 'LOG_LEVEL',
	LOG_ON = 'LOG_ON',
}

export enum RedisEnum {
	REDIS_URL = 'REDIS_URL',
	REDIS_PASSWORD = 'REDIS_PASSWORD',
	REDIS_USERNAME = 'REDIS_USERNAME',
}

/** 邮件（与 dnhyxc-ai 一致） */
export enum EmailEnum {
	EMAIL_TRANSPORT = 'EMAIL_TRANSPORT',
	EMAIL_FROM = 'EMAIL_FROM',
}
