export const API = {
	login: '/auth/login',
	register: '/auth/register',
	captcha: '/auth/createVerifyCode',
	profile: '/auth/profile',
	overview: '/dashboard/overview',
	users: '/user/getUsers',
	addUser: '/user/addUser',
	updateUser: '/user/updateUser',
	deleteUser: '/user/deleteUser',
	roles: '/roles/getRoles',
	createRole: '/roles/createRole',
	updateRole: '/roles/updateRole',
	deleteRole: '/roles/deleteRole',
	menus: '/menus/getMenus',
	createMenu: '/menus/createMenu',
	updateMenu: '/menus/updateMenu',
	deleteMenu: '/menus/deleteMenu',
	logs: '/logs/getLogs',
	aiUsers: '/ai-user/getUsers',
	health: '/health',
} as const;
